# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-31 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lifemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.TextField(blank=True, default='')),
                ('category', models.TextField(blank=True, default='')),
                ('state', models.TextField(blank=True, default='')),
                ('due_datehour', models.TextField(blank=True, default='')),
                ('rating', models.TextField(blank=True, default='')),
                ('tags', models.TextField(blank=True, default='')),
                ('desc', models.TextField(blank=True, default='')),
                ('image_url', models.TextField(blank=True, default='')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostgreTypeCheckModel',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('descr', models.CharField(blank=True, max_length=5000, null=True)),
                ('img_link', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('cdate', models.DateTimeField(blank=True, null=True)),
                ('udate', models.DateTimeField(blank=True, null=True)),
                ('ddate', models.DateTimeField(blank=True, null=True)),
                ('is_complete', models.NullBooleanField()),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=None, null=True)),
                ('category', models.TextField(default='', null=True)),
                ('state', models.TextField(null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
