# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-31 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostgreTypeCheckModel',
        ),
        migrations.AddField(
            model_name='lifemark',
            name='geo_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lifemark',
            name='geo_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
