# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, default='2018-01-01 00:00'),
            preserve_default=False,
        ),
    ]
