# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testmodel_cdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifemark',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lifemark',
            name='udate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
