# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-04 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180831_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifemark',
            name='u_geo_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lifemark',
            name='u_geo_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
