# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-04 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180904_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifemark',
            old_name='geo_lat',
            new_name='c_geo_lat',
        ),
        migrations.RenameField(
            model_name='lifemark',
            old_name='geo_lon',
            new_name='c_geo_lon',
        ),
    ]
