# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180712_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifemark',
            old_name='is_complete',
            new_name='state',
        ),
    ]
