# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180703_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifemark',
            name='due_date',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='lifemark',
            name='image_url',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='lifemark',
            name='link',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='lifemark',
            name='rating',
            field=models.TextField(default='', null=True),
        ),
    ]
