# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifemark',
            name='title',
            field=models.TextField(),
        ),
    ]
